#! /bin/sh

cd /etc/script/share
echo "Updating ipset DIRECT from direct_rules.txt and direct_extra.txt ..."

ipset flush DIRECT

if [ -e "../share/direct_rules.txt" ]; then
	/etc/script/bin/ipset-append.sh DIRECT ../share/direct_rules.txt
fi

if [ -e "../share/direct_extra.txt" ]; then
	/etc/script/bin/ipset-append.sh DIRECT ../share/direct_extra.txt
fi

echo "Updating ipset PASSWALL from passwall_rules.txt and passwall_extra.txt ..."

ipset flush PASSWALL

if [ -e "../share/passwall_rules.txt" ]; then
	/etc/script/bin/ipset-append.sh PASSWALL ../share/passwall_rules.txt
fi

if [ -e "../share/passwall_extra.txt" ]; then
	/etc/script/bin/ipset-append.sh PASSWALL ../share/passwall_extra.txt
fi

echo "Updating ipset BANLIST1 from banlist_rules.txt and banlist_extra.txt ..."

ipset flush BANLIST1

if [ -e "../share/banlist_rules.txt" ]; then
	/etc/script/bin/ipset-append.sh BANLIST1 ../share/banlist_rules.txt
fi

if [ -e "../share/banlist_extra.txt" ]; then
	/etc/script/bin/ipset-append.sh BANLIST1 ../share/banlist_extra.txt
fi

echo "Updating /etc/dnsmasq.d/50-rules.conf from dns_rules.txt and dns_extra.txt ..."

FN="/etc/dnsmasq.d/50-rules.conf"
echo "# generated by /etc/script/tools/update_rules.sh" > $FN

if [ -e "../share/dns_rules.txt" ]; then
	python3 /etc/script/lib/dnsmasq_convert.py dns_rules.txt 8.8.4.4 PASSWALL >> $FN
fi

if [ -e "../share/dns_extra.txt" ]; then
	python3 /etc/script/lib/dnsmasq_convert.py dns_extra.txt 8.8.4.4 PASSWALL >> $FN
fi

echo "Restarting dnsmasq"

systemctl restart dnsmasq

echo "Done"

