#! /bin/sh

cd /etc/script/share
echo "Updating ipset DIRECT from direct_rules.txt and direct_extra.txt ..."

ipset flush DIRECT

if [ -e "../share/direct_rules.txt" ]; then
	/etc/script/bin/ipset-append.sh DIRECT ../share/direct_rules.txt
fi

if [ -e "../share/direct_extra.txt" ]; then
	/etc/script/bin/ipset-append.sh DIRECT ../share/direct_extra.txt
fi

echo "Updating ipset VPN1 from vpn1_rules.txt and vpn1_extra.txt ..."

ipset flush VPN1

if [ -e "../share/vpn1_rules.txt" ]; then
	/etc/script/bin/ipset-append.sh VPN1 ../share/vpn1_rules.txt
fi

if [ -e "../share/vpn1_extra.txt" ]; then
	/etc/script/bin/ipset-append.sh VPN1 ../share/vpn1_extra.txt
fi

echo "Updating ipset VPN2 from vpn2_rules.txt and vpn2_extra.txt ..."

ipset flush VPN2

if [ -e "../share/vpn2_rules.txt" ]; then
	/etc/script/bin/ipset-append.sh VPN2 ../share/vpn2_rules.txt
fi

if [ -e "../share/vpn2_extra.txt" ]; then
	/etc/script/bin/ipset-append.sh VPN2 ../share/vpn2_extra.txt
fi

echo "Updating ipset BANLIST1 from banlist_rules.txt and banlist_extra.txt ..."

ipset flush BANLIST1

if [ -e "../share/banlist_rules.txt" ]; then
	/etc/script/bin/ipset-append.sh BANLIST1 ../share/banlist_rules.txt
fi

if [ -e "../share/banlist_extra.txt" ]; then
	/etc/script/bin/ipset-append.sh BANLIST1 ../share/banlist_extra.txt
fi

echo "Updating /etc/dnsmasq.d/50-rules-vpn1.conf from dns1_rules.txt and dns1_extra.txt ..."

FN="/etc/dnsmasq.d/50-rules-vpn1.conf"
echo "# generated by /etc/script/tools/update_rules.sh" > $FN

if [ -e "../share/dns1_rules.txt" ]; then
	python3 /etc/script/lib/dnsmasq_convert.py dns1_rules.txt 8.8.4.4 VPN1 >> $FN
fi

if [ -e "../share/dns1_extra.txt" ]; then
	python3 /etc/script/lib/dnsmasq_convert.py dns1_extra.txt 8.8.4.4 VPN1 >> $FN
fi

echo "Updating /etc/dnsmasq.d/50-rules-vpn2.conf from dns2_rules.txt and dns2_extra.txt ..."

FN="/etc/dnsmasq.d/50-rules-vpn2.conf"
echo "# generated by /etc/script/tools/update_rules.sh" > $FN

if [ -e "../share/dns2_rules.txt" ]; then
	python3 /etc/script/lib/dnsmasq_convert.py dns2_rules.txt 8.8.8.8 VPN2 >> $FN
fi

if [ -e "../share/dns2_extra.txt" ]; then
	python3 /etc/script/lib/dnsmasq_convert.py dns2_extra.txt 8.8.8.8 VPN2 >> $FN
fi


echo "Restarting dnsmasq"

systemctl restart dnsmasq

echo "Done"

